import { describe, expect, it, vi } from 'vitest';
import { BrokerSymbol, ScrapperTradeApi, StrategySpec, chartPath, suggestBrokerSymbols, validateStrategySpec } from './api';
describe('ScrapperTradeApi', () => {
  it('loads typed system state', async () => { const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({mode:'PAUSED',allowsNewEntries:false}),{status:200})); expect(await new ScrapperTradeApi('',fetcher).system()).toEqual({mode:'PAUSED',allowsNewEntries:false}); });
  it('normalizes the current host numeric enum contract', async () => { const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({mode:6}),{status:200})); expect(await new ScrapperTradeApi('',fetcher).system()).toEqual({mode:'EMERGENCY_LOCKED',allowsNewEntries:false}); });
  it('does not replace missing live capabilities with simulator data', async () => { const fetcher=vi.fn().mockResolvedValue(new Response('',{status:404})); await expect(new ScrapperTradeApi('',fetcher).mt5()).rejects.toEqual(expect.objectContaining({status:404})); });
  it('posts emergency stop through the host boundary', async () => { const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({mode:'EMERGENCY_LOCKED',allowsNewEntries:false}),{status:200})); await new ScrapperTradeApi('',fetcher).emergencyStop(); expect(fetcher).toHaveBeenCalledWith('/api/system/emergency-stop',expect.objectContaining({method:'POST'})); });
  it('preserves an API rejection reason for destructive controls', async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({reason:'Verified close workflow unavailable.'}),{status:409}));await expect(new ScrapperTradeApi('',fetcher).closeAll()).rejects.toEqual(expect.objectContaining({status:409,message:'Verified close workflow unavailable.'}));});
  it('ranks exact and broker-suffixed symbol suggestions and excludes blocked symbols',()=>{const symbol=(name:string,tradeAllowed=true)=>({name,tradeAllowed,description:'',currencyBase:'',currencyProfit:'',digits:2,point:.01,tickSize:.01,tickValue:1,contractSize:1,volumeMinimum:.01,volumeMaximum:1,volumeStep:.01,stopsLevelPoints:0}) satisfies BrokerSymbol;expect(suggestBrokerSymbols('XAUUSD',[symbol('XAUUSDm'),symbol('XAUUSD'),symbol('XAUUSD.bad',false)]).map(x=>x.name)).toEqual(['XAUUSD','XAUUSDm']);});
  it('rejects incomplete or over-authoritative strategy specifications',()=>{const strategy={id:'s1',name:'',version:1,status:'DRAFT',description:'',instruments:[],timeframes:[],regimes:[],entry:{all:[]},exit:{stopLoss:'',takeProfit:''},risk:{maxRiskFraction:.03,maxPositions:1},sourceIds:[],updatedAt:''} satisfies StrategySpec;expect(validateStrategySpec(strategy)).toEqual(expect.arrayContaining(['Name is required.','A stop-loss rule is required.','Strategy risk must be above 0 and no more than 2%.','At least one provenance source is required.']));});
  it('creates deterministic equity chart paths without inventing points',()=>{expect(chartPath([])).toBe('');expect(chartPath([100,110],100,50)).toBe('M0.0,50.0 L100.0,0.0');});
  it('approval calls validation workflow, not activation or execution',async()=>{const candidate={id:'c1',name:'Candidate',hypothesis:'',status:'APPROVED_FOR_VALIDATION',sourceCitations:[],ambiguities:[],createdAt:''};const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify(candidate),{status:200}));await new ScrapperTradeApi('',fetcher).approveCandidateForValidation('c1');expect(fetcher).toHaveBeenCalledWith('/api/research/candidates/c1/approve-validation',expect.objectContaining({method:'POST'}));});
});
