import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, AlertTriangle, BarChart3, BookOpen, Bot, ChevronRight, CircleDollarSign, FlaskConical, Gauge, HeartPulse, LayoutDashboard, Menu, Pause, Settings, ShieldAlert, Target, X } from 'lucide-react';
import './styles.css';

type NavKey = 'Command Centre'|'Markets'|'Positions'|'Strategies'|'Research Lab'|'Knowledge'|'Health'|'Settings';
const nav: [NavKey, React.ElementType][] = [['Command Centre',LayoutDashboard],['Markets',BarChart3],['Positions',CircleDollarSign],['Strategies',Target],['Research Lab',FlaskConical],['Knowledge',BookOpen],['Health',HeartPulse],['Settings',Settings]];
const markets = [
  {symbol:'XAUUSD', broker:'XAUUSDm', price:'2,387.42', spread:'1.8', regime:'TRENDING UP', risk:'0.42%', pnl:'+R 1.24', state:'Active'},
  {symbol:'EURUSD', broker:'EURUSD', price:'1.08462', spread:'0.7', regime:'RANGING', risk:'0.18%', pnl:'—', state:'Active'},
  {symbol:'USTEC', broker:'USTECm', price:'18,542.1', spread:'2.1', regime:'HIGH VOL', risk:'0.00%', pnl:'—', state:'Avoided'}
];
const positions = [{symbol:'XAUUSDm',side:'BUY',strategy:'Trend Pullback',entry:'2,378.60',sl:'2,369.20',tp:'2,396.90',pnl:'+$184.20',risk:'$94.00'}];

function Confirm({kind,onClose,onConfirm}:{kind:'close'|'emergency',onClose:()=>void,onConfirm:()=>void}) {
  const emergency=kind==='emergency'; const [phrase,setPhrase]=useState('');
  return <div className="scrim" role="dialog" aria-modal="true"><div className="modal"><button className="icon close" onClick={onClose} aria-label="Close"><X/></button><span className={'modal-icon '+(emergency?'danger':'warn')}>{emergency?<ShieldAlert/>:<AlertTriangle/>}</span><h2>{emergency?'Activate emergency stop?':'Close every position?'}</h2><p>{emergency?'New commands will be locked, pending orders cancelled, and configured positions closed. Only you can reactivate trading.':'New entries will pause first. All pending orders and open positions will then be closed and verified.'}</p>{emergency&&<><label htmlFor="confirm">Type <strong>EMERGENCY</strong> to confirm</label><input id="confirm" autoFocus value={phrase} onChange={e=>setPhrase(e.target.value)} /></>}<div className="modal-actions"><button className="secondary" onClick={onClose}>Keep trading</button><button className="danger-button" disabled={emergency&&phrase!=='EMERGENCY'} onClick={onConfirm}>{emergency?'Lock and close':'Pause and close all'}</button></div></div></div>
}

function SetupWizard({done}:{done:()=>void}) { const [step,setStep]=useState(0); const steps=['Welcome','Connection','Safety','Ready']; return <div className="wizard"><div className="wizard-panel"><div className="brand"><span className="logo"><Gauge/></span><div>SCRAPPER<span>TRADE</span></div></div><div className="stepper">{steps.map((s,i)=><div className={i<=step?'active':''} key={s}><b>{i+1}</b><span>{s}</span></div>)}</div><div className="wizard-card">{step===0&&<><span className="eyebrow">LOCAL CONTROL CENTRE</span><h1>Trade deliberately.<br/><em>Learn continuously.</em></h1><p>ScrapperTrade keeps execution deterministic and risk boundaries under your control. We’ll start safely in the built-in simulator.</p><div className="safety-note"><ShieldAlert/><div><strong>Real-money trading is locked</strong><span>This setup cannot enable live trading. Demo verification is required before any MT5 order.</span></div></div></>}{step===1&&<><span className="eyebrow">CONNECTION CHECK</span><h1>Start without MT5.</h1><p>The simulator is ready now. Connect MetaTrader 5 later from Settings when a demo account and the ScrapperTrade EA are available.</p><div className="check-list"><div><i className="ok">✓</i><span><strong>Simulator ready</strong><small>Market playback and safe order lifecycle</small></span></div><div><i>!</i><span><strong>MT5 not detected</strong><small>No action required to explore the platform</small></span></div></div></>}{step===2&&<><span className="eyebrow">HARD SAFETY POLICY</span><h1>Boundaries first.</h1><p>Strategies and AI operate below your permissions. Neither can change hard risk policy, unlock an emergency stop, or enable a disallowed market.</p><div className="policy"><span>Risk per trade <b>0.50%</b></span><span>Daily loss limit <b>2.00%</b></span><span>Open positions <b>Max 3</b></span></div></>}{step===3&&<><span className="eyebrow">SETUP COMPLETE</span><h1>Your control centre is ready.</h1><p>Simulator mode includes representative markets and one open example position, so every screen has meaningful data from the start.</p><div className="ready"><Bot/><div><strong>SIMULATOR / DEMO-SAFE</strong><span>No broker orders can be sent</span></div></div></>}<button className="primary next" onClick={()=>step<3?setStep(step+1):done()}>{step<3?'Continue':'Open command centre'}<ChevronRight/></button></div></div></div> }

function App(){ const [page,setPage]=useState<NavKey>('Command Centre'),[paused,setPaused]=useState(false),[confirm,setConfirm]=useState<'close'|'emergency'|null>(null),[locked,setLocked]=useState(false),[wizard,setWizard]=useState(()=>localStorage.getItem('st-onboarded')!=='1'),[menu,setMenu]=useState(false);
  const finish=()=>{localStorage.setItem('st-onboarded','1');setWizard(false)}; if(wizard)return <SetupWizard done={finish}/>;
  return <div className="app"><aside className={menu?'open':''}><div className="brand"><span className="logo"><Gauge/></span><div>SCRAPPER<span>TRADE</span></div><button className="icon mobile-close" onClick={()=>setMenu(false)}><X/></button></div><div className="mode"><i></i><span>SIMULATOR MODE<small>Demo-safe environment</small></span></div><nav>{nav.map(([name,Icon])=><button key={name} className={page===name?'active':''} onClick={()=>{setPage(name);setMenu(false)}}><Icon/>{name}</button>)}</nav><div className="side-health"><span><Activity/> System health</span><b>All systems operational</b><small>Last check 8s ago</small></div></aside><main><header><button className="icon hamburger" onClick={()=>setMenu(true)}><Menu/></button><div><span>LOCAL INSTANCE</span><b>Simulator · Demo account</b></div><div className="header-status"><i></i><span>MARKET DATA<strong>LIVE</strong></span></div><button className="avatar">JD</button></header><section className="content"><div className="title"><div><span className="eyebrow">FRIDAY · LONDON / NEW YORK OVERLAP</span><h1>{page}</h1><p>{page==='Command Centre'?'Live operations, portfolio risk and system control.':`Review and manage ${page.toLowerCase()} safely.`}</p></div>{page==='Command Centre'&&<div className="actions"><button className={'pause '+(paused?'active':'')} onClick={()=>setPaused(!paused)}><Pause/>{paused?'Resume new trades':'Pause new trades'}</button><button className="outline-danger" onClick={()=>setConfirm('close')}>Close all</button><button className="danger-button" onClick={()=>setConfirm('emergency')}><ShieldAlert/>Emergency stop</button></div>}</div>{locked&&<div className="locked"><ShieldAlert/><div><b>EMERGENCY LOCK ACTIVE</b><span>All execution commands are blocked. Reactivation requires an explicit user safety review.</span></div></div>}{paused&&!locked&&<div className="paused"><Pause/><b>New entries paused</b><span>Existing positions remain protected and managed.</span></div>}
  {page==='Command Centre'?<Dashboard/>:<Placeholder page={page}/>}</section></main>{confirm&&<Confirm kind={confirm} onClose={()=>setConfirm(null)} onConfirm={()=>{if(confirm==='emergency')setLocked(true);setPaused(true);setConfirm(null)}}/>}</div> }

function Dashboard(){return <><div className="kpis"><Metric label="EQUITY" value="$25,184.20" delta="+$184.20 today"/><Metric label="OPEN RISK" value="0.60%" delta="$151 of $500 limit"/><Metric label="OPEN POSITIONS" value="1 / 3" delta="Across 1 market"/><Metric label="SYSTEM STATE" value="RUNNING" delta="Simulator healthy" good/></div><div className="grid"><div className="panel span2"><PanelTitle title="Trading universe" meta="3 configured markets"/><div className="market-table"><div className="tr head"><span>MARKET</span><span>PRICE / SPREAD</span><span>REGIME</span><span>OPEN RISK</span><span>STATUS</span></div>{markets.map(m=><div className="tr" key={m.symbol}><span><b>{m.symbol}</b><small>{m.broker}</small></span><span><b>{m.price}</b><small>{m.spread} spread</small></span><span><em>{m.regime}</em></span><span><b>{m.risk}</b><small className="positive">{m.pnl}</small></span><span><i className={m.state==='Active'?'status ok':'status'}>{m.state}</i></span></div>)}</div></div><div className="panel risk"><PanelTitle title="Portfolio risk" meta="Conservative demo policy"/><div className="risk-ring"><div><b>30%</b><span>OF LIMIT</span></div></div><div className="risk-row"><span>Open risk<b>$151</b></span><span>Available<b>$349</b></span></div><div className="bar"><i style={{width:'30%'}}/></div><small>Daily combined loss limit: $500</small></div><div className="panel span2"><PanelTitle title="Open positions" meta="1 position"/><div className="position"><div><span className="buy">BUY</span><b>{positions[0].symbol}</b><small>{positions[0].strategy}</small></div><span>ENTRY<b>{positions[0].entry}</b></span><span>SL / TP<b>{positions[0].sl} / {positions[0].tp}</b></span><span>RISK<b>{positions[0].risk}</b></span><span className="positive">UNREALIZED<b>{positions[0].pnl}</b></span><button className="secondary">Manage</button></div></div><div className="panel"><PanelTitle title="Execution health" meta="Updated now"/><div className="health-list"><span><i className="ok"></i>Host API <b>Healthy</b></span><span><i className="ok"></i>Simulator <b>Connected</b></span><span><i className="ok"></i>Market data <b>Fresh · 0.3s</b></span><span><i className="ok"></i>Command queue <b>Empty</b></span></div></div></div></>}
function Metric({label,value,delta,good}:{label:string,value:string,delta:string,good?:boolean}){return <div className="metric"><span>{label}</span><b className={good?'positive':''}>{value}</b><small>{delta}</small></div>}
function PanelTitle({title,meta}:{title:string,meta:string}){return <div className="panel-title"><h2>{title}</h2><span>{meta}</span></div>}
function Placeholder({page}:{page:NavKey}){return <div className="panel empty"><div className="empty-icon"><Activity/></div><h2>{page}</h2><p>This workspace will populate from the local API. Simulator data remains available while MT5 is disconnected.</p><button className="primary">Refresh simulator data</button></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
