import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,AlertTriangle,Cable,Check,Gauge,LayoutDashboard,Link2,Menu,Pause,RefreshCw,Settings,ShieldAlert,Unplug,X} from 'lucide-react';
import {ApiError,InstrumentMapping,Mt5Status,ScrapperTradeApi,SystemStatus,isExplicitSimulator} from './api';
import {DestructiveAction,confirmationPhrase,destructivePhraseValid} from './safety';
import './styles.css';
const api=new ScrapperTradeApi(import.meta.env.VITE_API_BASE_URL??''); type LoadState='loading'|'ready'|'error';

function Confirm({action,busy,error,onClose,onConfirm}:{action:DestructiveAction;busy:boolean;error?:string;onClose:()=>void;onConfirm:()=>void}){const [phrase,setPhrase]=useState('');const required=confirmationPhrase(action);return <div className="scrim" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&!busy&&onClose()}><div className="modal" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title"><button className="icon close" onClick={onClose} disabled={busy} aria-label="Cancel action"><X/></button><span className="modal-icon danger"><ShieldAlert/></span><h2 id="confirm-title">{action==='emergency'?'Activate emergency stop?':'Close every position?'}</h2><p>{action==='emergency'?'The host will lock execution. Reactivation remains a separate, explicit user action.':'The host will pause new entries, request closure, and verify every broker result.'}</p><label htmlFor="confirm-phrase">Type <strong>{required}</strong> to confirm</label><input id="confirm-phrase" autoFocus autoComplete="off" value={phrase} onChange={e=>setPhrase(e.target.value)}/>{error&&<p className="inline-error" role="alert">{error}</p>}<div className="modal-actions"><button className="secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="danger-button" disabled={busy||!destructivePhraseValid(action,phrase)} onClick={onConfirm}>{busy?'Waiting for host…':action==='emergency'?'Lock execution':'Pause and close all'}</button></div></div></div>}
function StatusPill({tone,children}:{tone:'ok'|'bad'|'neutral';children:React.ReactNode}){return <span className={`status-pill ${tone}`}><i/>{children}</span>}
function Skeleton({rows=3}:{rows?:number}){return <div className="skeleton" aria-label="Loading">{Array.from({length:rows},(_,i)=><i key={i}/>)}</div>}
function ErrorState({message,retry}:{message:string;retry:()=>void}){return <div className="state-card error-state" role="alert"><AlertTriangle/><div><b>Live data unavailable</b><span>{message}</span></div><button className="secondary" onClick={retry}><RefreshCw/>Retry</button></div>}
function CheckRow({ok,label,detail}:{ok:boolean;label:string;detail:string}){return <div className="check-row"><span className={ok?'check-ok':'check-blocked'}>{ok?<Check/>:<X/>}</span><div><b>{label}</b><small>{detail}</small></div><StatusPill tone={ok?'ok':'bad'}>{ok?'Ready':'Blocked'}</StatusPill></div>}

function MappingPanel({state,mappings,error,reload}:{state:LoadState;mappings:InstrumentMapping[];error?:string;reload:()=>void}){if(state==='loading')return <section className="panel"><div className="panel-title"><h2>Instrument mapping</h2></div><Skeleton rows={4}/></section>;if(state==='error')return <section className="panel"><div className="panel-title"><h2>Instrument mapping</h2></div><ErrorState message={error!} retry={reload}/></section>;return <section className="panel"><div className="panel-title"><div><h2>Instrument mapping</h2><p>Logical instruments must resolve to discovered broker symbols before trading.</p></div><button className="secondary" onClick={reload}><RefreshCw/>Refresh</button></div>{mappings.length===0?<div className="empty"><Unplug/><h3>No instruments configured</h3><p>Add an instrument after MT5 symbol discovery is available. Nothing is enabled automatically.</p></div>:<div className="mapping-table"><div className="mapping-row head"><span>Instrument</span><span>Broker symbol</span><span>Validation</span><span>Trading</span></div>{mappings.map(m=><div className="mapping-row" key={m.id}><span><b>{m.logicalSymbol}</b><small>Logical symbol</small></span><span><b>{m.brokerSymbol||'Not mapped'}</b>{m.suggestedSymbol&&!m.brokerSymbol&&<small>Suggested: {m.suggestedSymbol}</small>}</span><span><StatusPill tone={m.valid?'ok':'bad'}>{m.valid?'Validated':'Blocked'}</StatusPill></span><span><b>{m.enabled&&m.valid?'Enabled':'Disabled'}</b></span></div>)}</div>}</section>}

function App(){const simulator=useMemo(()=>isExplicitSimulator(),[]);const [load,setLoad]=useState<LoadState>('loading'),[system,setSystem]=useState<SystemStatus>(),[mt5,setMt5]=useState<Mt5Status>(),[systemError,setSystemError]=useState(''),[mt5Error,setMt5Error]=useState(''),[mappingLoad,setMappingLoad]=useState<LoadState>('loading'),[mappings,setMappings]=useState<InstrumentMapping[]>([]),[mappingError,setMappingError]=useState(''),[confirm,setConfirm]=useState<DestructiveAction>(),[actionBusy,setActionBusy]=useState(false),[actionError,setActionError]=useState(''),[menu,setMenu]=useState(false);
 const loadStatus=useCallback(async()=>{setLoad('loading');setSystemError('');setMt5Error('');const [s,m]=await Promise.allSettled([api.system(),api.mt5()]);if(s.status==='fulfilled')setSystem(s.value);else setSystemError(s.reason.message);if(m.status==='fulfilled')setMt5(m.value);else setMt5Error(m.reason.message);setLoad(s.status==='rejected'?'error':'ready')},[]);
 const loadMappings=useCallback(async()=>{setMappingLoad('loading');setMappingError('');try{setMappings(await api.instruments());setMappingLoad('ready')}catch(e){setMappingError((e as ApiError).message);setMappingLoad('error')}},[]);
 useEffect(()=>{void loadStatus();void loadMappings();const timer=window.setInterval(loadStatus,10000);return()=>clearInterval(timer)},[loadStatus,loadMappings]);
 const runControl=async(kind:'pause'|'start')=>{setActionError('');setActionBusy(true);try{setSystem(await(kind==='pause'?api.pause():api.start()))}catch(e){setActionError((e as ApiError).message)}finally{setActionBusy(false)}};
 const runDestructive=async()=>{if(!confirm)return;setActionError('');setActionBusy(true);try{if(confirm==='emergency')setSystem(await api.emergencyStop());else await api.closeAll();setConfirm(undefined);await loadStatus()}catch(e){setActionError((e as ApiError).message)}finally{setActionBusy(false)}};
 const locked=system?.mode==='EMERGENCY_LOCKED'||mt5?.emergencyLocked,paused=system?.mode==='PAUSED',heartbeatFresh=mt5?.heartbeatAt?Date.now()-Date.parse(mt5.heartbeatAt)<30000:false,mt5Safe=!!mt5?.connected&&mt5.accountMode==='DEMO'&&heartbeatFresh;
 return <div className="app"><aside className={menu?'open':''}><div className="brand"><span className="logo"><Gauge/></span><div>SCRAPPER<span>TRADE</span></div><button className="icon mobile-close" onClick={()=>setMenu(false)} aria-label="Close navigation"><X/></button></div><div className={`mode ${simulator?'sim':mt5Safe?'':'unsafe'}`}><i/><span>{simulator?'EXPLICIT SIMULATOR':mt5Safe?'MT5 DEMO VERIFIED':'EXECUTION BLOCKED'}<small>{simulator?'Enabled by startup configuration':mt5Safe?'Fresh positive demo heartbeat':'Awaiting safe broker connection'}</small></span></div><nav><button className="active"><LayoutDashboard/>Command Centre</button><button><Link2/>Instruments</button><button><Activity/>Health</button><button><Settings/>Settings</button></nav><div className="side-health"><span><Activity/> Local host</span><b>{load==='ready'?'API responding':load==='loading'?'Checking…':'Unavailable'}</b><small>Auto-refresh every 10 seconds</small></div></aside>
 <main><header><button className="icon hamburger" onClick={()=>setMenu(true)} aria-label="Open navigation"><Menu/></button><div><span>LOCAL INSTANCE</span><b>{simulator?'Simulator explicitly enabled':'Live local API'}</b></div><button className="secondary refresh" onClick={()=>{void loadStatus();void loadMappings()}}><RefreshCw/>Refresh</button></header><section className="content"><div className="title"><div><span className="eyebrow">SAFETY-FIRST OPERATIONS</span><h1>Command Centre</h1><p>Connection truth, execution authority, and broker mapping at a glance.</p></div><div className="actions"><button className={`pause ${paused?'active':''}`} disabled={actionBusy||locked||load!=='ready'} onClick={()=>void runControl(paused?'start':'pause')}><Pause/>{paused?'Request resume':'Pause new trades'}</button><button className="outline-danger" disabled={actionBusy||load!=='ready'} onClick={()=>{setActionError('');setConfirm('close')}}>Close all</button><button className="danger-button" disabled={actionBusy||locked||load!=='ready'} onClick={()=>{setActionError('');setConfirm('emergency')}}><ShieldAlert/>Emergency stop</button></div></div>
 {actionError&&!confirm&&<div className="banner error" role="alert"><AlertTriangle/>{actionError}</div>}{locked&&<div className="locked"><ShieldAlert/><div><b>EMERGENCY LOCK ACTIVE</b><span>All execution commands are blocked. Only explicit user reactivation can unlock trading.</span></div></div>}{paused&&!locked&&<div className="paused"><Pause/><b>New entries paused</b><span>Protective position management may continue.</span></div>}
 {load==='loading'?<div className="kpis three"><Skeleton/><Skeleton/><Skeleton/></div>:load==='error'?<ErrorState message={systemError} retry={loadStatus}/>:<div className="kpis three"><article className="metric"><span>SYSTEM STATE</span><b>{system?.mode??'UNKNOWN'}</b><small>{system?.allowsNewEntries?'New entries permitted by host':'New entries blocked by host'}</small></article><article className="metric"><span>MT5 CONNECTION</span><b>{mt5?.connected?'CONNECTED':'NOT VERIFIED'}</b><small>{mt5Error||(heartbeatFresh?'Heartbeat fresh':'No fresh heartbeat')}</small></article><article className="metric"><span>ACCOUNT SAFETY</span><b className={mt5Safe?'positive':'negative'}>{mt5Safe?'DEMO VERIFIED':'FAIL CLOSED'}</b><small>{mt5?`${mt5.accountMode} · ${mt5.accountType??'Account type unknown'}`:'No broker account metadata'}</small></article></div>}
 <div className="connection-grid"><section className="panel"><div className="panel-title"><div><h2>First-run readiness</h2><p>Every execution dependency must be positively verified.</p></div></div><div className="check-list"><CheckRow ok={load==='ready'} label="Local host API" detail={load==='ready'?'Responding':systemError||'Checking connection'}/><CheckRow ok={!!mt5?.connected} label="MT5 terminal" detail={mt5Error||(mt5?.terminal??'Connection not reported')}/><CheckRow ok={mt5Safe} label="Demo safety gate" detail={mt5Safe?'Fresh DEMO heartbeat':'Trading remains blocked'}/><CheckRow ok={!!mt5?.emergencyLocked} label="Emergency lock" detail={mt5?.emergencyLocked?'Locked at EA boundary':'State not positively locked'}/></div></section><section className="panel"><div className="panel-title"><div><h2>Connection detail</h2><p>Unknown and stale values never imply permission.</p></div></div>{mt5?<dl className="details"><div><dt>Terminal</dt><dd>{mt5.terminal||'Not reported'}</dd></div><div><dt>Broker account</dt><dd>{mt5.accountMode}</dd></div><div><dt>Position mode</dt><dd>{mt5.accountType||'UNKNOWN'}</dd></div><div><dt>Heartbeat</dt><dd>{mt5.heartbeatAt?new Date(mt5.heartbeatAt).toLocaleString():'Not reported'}</dd></div></dl>:<div className="empty compact"><Cable/><h3>No MT5 status available</h3><p>{mt5Error||'Waiting for the local bridge.'}</p></div>}</section></div><MappingPanel state={mappingLoad} mappings={mappings} error={mappingError} reload={loadMappings}/></section></main>{confirm&&<Confirm action={confirm} busy={actionBusy} error={actionError} onClose={()=>!actionBusy&&setConfirm(undefined)} onConfirm={()=>void runDestructive()}/>}</div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
