using ScrapperTrade.Domain;
namespace ScrapperTrade.Quant;
public sealed record SizingResult(bool Success,decimal Volume,decimal ActualRisk,string? Error=null);
public static class PositionSizer { public static SizingResult Calculate(decimal budget,decimal entry,decimal stop,SymbolMetadata s){if(budget<=0||entry<=0||stop<=0||entry==stop)return Bad("Risk budget and distinct positive prices are required.");if(s.TickSize<=0||s.TickValue<=0||s.VolumeMin<=0||s.VolumeMax<s.VolumeMin||s.VolumeStep<=0)return Bad("Broker metadata is incomplete or invalid.");var loss=Math.Abs(entry-stop)/s.TickSize*s.TickValue;var raw=budget/loss;if(raw<s.VolumeMin)return Bad("Minimum broker volume exceeds the risk budget.");var steps=decimal.Floor((raw-s.VolumeMin)/s.VolumeStep);var volume=Math.Min(s.VolumeMin+Math.Max(0,steps)*s.VolumeStep,s.VolumeMax);return new(true,volume,volume*loss);}static SizingResult Bad(string e)=>new(false,0,0,e); }
public sealed record Candle(DateTimeOffset Time,decimal Open,decimal High,decimal Low,decimal Close,decimal Spread=0);
public static class Indicators { public static decimal Ema(IEnumerable<decimal> values,int period){var d=values.ToArray();if(period<=0||d.Length<period)throw new ArgumentException("Insufficient data or invalid period.");var e=d.Take(period).Average();var k=2m/(period+1);foreach(var v in d.Skip(period))e=v*k+e*(1-k);return e;} public static decimal Atr(IReadOnlyList<Candle> c,int period){if(period<=0||c.Count<period+1)throw new ArgumentException("Insufficient data or invalid period.");return Enumerable.Range(c.Count-period,period).Average(i=>Math.Max(c[i].High-c[i].Low,Math.Max(Math.Abs(c[i].High-c[i-1].Close),Math.Abs(c[i].Low-c[i-1].Close))));}}
public sealed record StrategySpec(string Id,int Version,int FastEma,int SlowEma,decimal StopAtr,decimal TargetRiskMultiple,IReadOnlySet<MarketRegime> Regimes);
public static class StrategyValidator { public static IReadOnlyList<string> Validate(StrategySpec s){var e=new List<string>();if(string.IsNullOrWhiteSpace(s.Id))e.Add("Id required.");if(s.Version<1)e.Add("Version invalid.");if(s.FastEma<2||s.SlowEma<=s.FastEma)e.Add("EMA periods invalid.");if(s.StopAtr<=0||s.TargetRiskMultiple<1)e.Add("Risk parameters invalid.");if(s.Regimes.Count==0||s.Regimes.Contains(MarketRegime.Unknown))e.Add("Explicit regimes required.");return e;} }
public sealed record BacktestTrade(DateTimeOffset Opened,DateTimeOffset Closed,Side Side,decimal Entry,decimal Exit,decimal R);
public sealed record BacktestResult(IReadOnlyList<BacktestTrade> Trades,decimal ExpectancyR,decimal WinRate,decimal ProfitFactor,decimal MaximumDrawdownR);
public sealed class DeterministicBacktester { public BacktestResult Run(StrategySpec s,IReadOnlyList<Candle> c){var errors=StrategyValidator.Validate(s);if(errors.Count>0)throw new ArgumentException(string.Join(" ",errors));var t=new List<BacktestTrade>();for(var i=s.SlowEma;i<c.Count-1;i++){var fast=Indicators.Ema(c.Take(i+1).Select(x=>x.Close),s.FastEma);var slow=Indicators.Ema(c.Take(i+1).Select(x=>x.Close),s.SlowEma);var pf=Indicators.Ema(c.Take(i).Select(x=>x.Close),s.FastEma);var ps=Indicators.Ema(c.Take(i).Select(x=>x.Close),s.SlowEma);if(!(pf<=ps&&fast>slow))continue;var entry=c[i].Close+c[i].Spread;var atr=Indicators.Atr(c.Take(i+1).ToArray(),Math.Min(14,i));var stop=entry-atr*s.StopAtr;var target=entry+(entry-stop)*s.TargetRiskMultiple;for(var j=i+1;j<c.Count;j++){decimal? exit=null;if(c[j].Low<=stop&&c[j].High>=target)exit=stop;else if(c[j].Low<=stop)exit=stop;else if(c[j].High>=target)exit=target;else if(j==c.Count-1)exit=c[j].Close;if(exit is not null){t.Add(new(c[i].Time,c[j].Time,Side.Buy,entry,exit.Value,(exit.Value-entry)/(entry-stop)));i=j;break;}}}var w=t.Where(x=>x.R>0).ToArray();var l=t.Where(x=>x.R<=0).ToArray();var gw=w.Sum(x=>x.R);var gl=Math.Abs(l.Sum(x=>x.R));decimal eq=0,peak=0,dd=0;foreach(var x in t){eq+=x.R;peak=Math.Max(peak,eq);dd=Math.Max(dd,peak-eq);}return new(t,t.Count==0?0:t.Average(x=>x.R),t.Count==0?0:(decimal)w.Length/t.Count,gl==0?(gw>0?decimal.MaxValue:0):gw/gl,dd);} }
