// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScrapperTrade.Infrastructure.Persistence;

#nullable disable

namespace ScrapperTrade.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ScrapperTradeDbContext))]
    [Migration("20260821113900_StrategyResearchGovernance")]
    partial class StrategyResearchGovernance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("ScrapperTrade.Infrastructure.Persistence.AuditLogRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.Persistence.BrokerSymbolMetadataRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ContractSize")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopLevel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TickValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VolumeMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VolumeMin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VolumeStep")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId", "BrokerSymbol")
                        .IsUnique();

                    b.ToTable("broker_symbol_metadata", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.Persistence.ConfigurationEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("configuration", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.Persistence.ExposureGroupRecord", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxRiskFraction")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxSameDirectionRiskFraction")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("exposure_groups", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.Persistence.InstrumentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowLong")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowShort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrokerSymbol")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExposureGroupCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogicalSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxConcurrentPositions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TradingSessionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogicalSymbol")
                        .IsUnique();

                    b.ToTable("instruments", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.Persistence.PositionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerPositionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExposureGroupCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogicalSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RiskAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrokerPositionId")
                        .IsUnique();

                    b.HasIndex("LogicalSymbol", "Status");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.Persistence.RiskPolicyChangeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FromVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("risk_policy_changes", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.Persistence.RiskPolicyVersionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("risk_policy_versions", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.Persistence.SystemEventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredAt");

                    b.ToTable("system_events", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.Persistence.TradeEventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SignalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("PositionId");

                    b.HasIndex("SignalId");

                    b.ToTable("trade_events", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.BacktestMetricRecord", b =>
                {
                    b.Property<Guid>("BacktestRunId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectancyR")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaximumDrawdownFraction")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetReturnFraction")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProfitFactor")
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("BacktestRunId");

                    b.ToTable("backtest_metrics", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.BacktestRunRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CostModelJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatasetReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOutOfSample")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StrategyVersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyVersionId");

                    b.ToTable("backtest_runs", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.BacktestTradeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BacktestRunId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EnteredAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExitedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RealisedR")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId");

                    b.ToTable("backtest_trades", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.ResearchCandidateProvenanceRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Citation")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResearchCandidateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResearchCandidateId");

                    b.ToTable("research_candidate_provenance", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.ResearchCandidateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AmbiguitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasUnresolvedAmbiguities")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hypothesis")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StrategyVersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyVersionId");

                    b.ToTable("research_candidates", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.ShadowComparisonRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChallengerMetricsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChallengerVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChampionMetricsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChampionVersionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionEvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChallengerVersionId");

                    b.HasIndex("ChampionVersionId", "ChallengerVersionId");

                    b.ToTable("shadow_comparisons", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyActivationRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StrategyDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StrategyVersionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserConfirmationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyDefinitionId")
                        .IsUnique()
                        .HasFilter("DeactivatedAt IS NULL");

                    b.HasIndex("StrategyVersionId");

                    b.HasIndex("UserConfirmationId")
                        .IsUnique();

                    b.ToTable("strategy_activations", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyDefinitionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("strategy_definitions", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyGovernanceAuditRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConfirmationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StrategyVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmationId")
                        .IsUnique()
                        .HasFilter("ConfirmationId IS NOT NULL");

                    b.HasIndex("StrategyVersionId");

                    b.ToTable("strategy_governance_audit", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyLineageRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ChildVersionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResearchCandidateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildVersionId");

                    b.HasIndex("ResearchCandidateId");

                    b.HasIndex("ParentVersionId", "ChildVersionId")
                        .IsUnique();

                    b.ToTable("strategy_lineage", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyValidationRunRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StrategyVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyVersionId", "ValidationKind");

                    b.ToTable("strategy_validation_runs", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecificationHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecificationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StrategyDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationHash");

                    b.HasIndex("StrategyDefinitionId", "Version")
                        .IsUnique();

                    b.ToTable("strategy_versions", (string)null);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.Persistence.BrokerSymbolMetadataRecord", b =>
                {
                    b.HasOne("ScrapperTrade.Infrastructure.Persistence.InstrumentRecord", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.BacktestMetricRecord", b =>
                {
                    b.HasOne("ScrapperTrade.Infrastructure.StrategyGovernance.BacktestRunRecord", "BacktestRun")
                        .WithOne("Metrics")
                        .HasForeignKey("ScrapperTrade.Infrastructure.StrategyGovernance.BacktestMetricRecord", "BacktestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestRun");
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.BacktestRunRecord", b =>
                {
                    b.HasOne("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyVersionRecord", "StrategyVersion")
                        .WithMany()
                        .HasForeignKey("StrategyVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StrategyVersion");
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.BacktestTradeRecord", b =>
                {
                    b.HasOne("ScrapperTrade.Infrastructure.StrategyGovernance.BacktestRunRecord", "BacktestRun")
                        .WithMany("Trades")
                        .HasForeignKey("BacktestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestRun");
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.ResearchCandidateProvenanceRecord", b =>
                {
                    b.HasOne("ScrapperTrade.Infrastructure.StrategyGovernance.ResearchCandidateRecord", "ResearchCandidate")
                        .WithMany("Provenance")
                        .HasForeignKey("ResearchCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchCandidate");
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.ResearchCandidateRecord", b =>
                {
                    b.HasOne("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyVersionRecord", "StrategyVersion")
                        .WithMany()
                        .HasForeignKey("StrategyVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StrategyVersion");
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.ShadowComparisonRecord", b =>
                {
                    b.HasOne("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("ChallengerVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("ChampionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyActivationRecord", b =>
                {
                    b.HasOne("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyDefinitionRecord", null)
                        .WithMany()
                        .HasForeignKey("StrategyDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("StrategyVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyGovernanceAuditRecord", b =>
                {
                    b.HasOne("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("StrategyVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyLineageRecord", b =>
                {
                    b.HasOne("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("ChildVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("ParentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScrapperTrade.Infrastructure.StrategyGovernance.ResearchCandidateRecord", null)
                        .WithMany()
                        .HasForeignKey("ResearchCandidateId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyValidationRunRecord", b =>
                {
                    b.HasOne("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyVersionRecord", "StrategyVersion")
                        .WithMany()
                        .HasForeignKey("StrategyVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StrategyVersion");
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyVersionRecord", b =>
                {
                    b.HasOne("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyDefinitionRecord", "StrategyDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("StrategyDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StrategyDefinition");
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.BacktestRunRecord", b =>
                {
                    b.Navigation("Metrics");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.ResearchCandidateRecord", b =>
                {
                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("ScrapperTrade.Infrastructure.StrategyGovernance.StrategyDefinitionRecord", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
